/**
 * Notification type constants
 * Requirements: 38.4, 38.5, 38.6, 38.7, 38.8, 38.9
 */
export const NotificationTypes = {
  SHIFT_ASSIGNED: 'SHIFT_ASSIGNED',
  SHIFT_MODIFIED: 'SHIFT_MODIFIED',
  SHIFT_DELETED: 'SHIFT_DELETED',
  SWAP_REQUEST_CREATED: 'SWAP_REQUEST_CREATED',
  SWAP_REQUEST_APPROVED: 'SWAP_REQUEST_APPROVED',
  SWAP_REQUEST_REJECTED: 'SWAP_REQUEST_REJECTED',
  SCHEDULE_PUBLISHED: 'SCHEDULE_PUBLISHED',
  OVERTIME_APPROACHING: 'OVERTIME_APPROACHING',
  AVAILABILITY_CHANGED: 'AVAILABILITY_CHANGED',
} as const;

export type NotificationType = (typeof NotificationTypes)[keyof typeof NotificationTypes];
